# Generated by Django 3.1.5 on 2021-01-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Stock_update',
        ),
    ]
